ui: tape
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: 8.1..latest
  - name: safari
    version: -2..latest
